# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Auto-label Job
on:
  pull_request_target

jobs:
  create-automerge-label:
    runs-on: ubuntu-latest
    steps: 
      - name: Add Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge

  create-repository-dispatch:
    needs: create-automerge-label
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: ['knot-test-organization/prueba']

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.OWNER_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: approve-event
          client-payload: '{"repository": "${{ github.event.repository.name }}", "owner": "${{ github.event.repository.owner.login }}",  "pull_number": ${{ github.event.number }}}'
