# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Auto-label Job
on:
  pull_request:
    types: [labeled]

jobs:
  verify-automerge-label:
    runs-on: ubuntu-latest
    steps: 
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "automerge"
          exit_type: failure
      # - name: Add Label
      #   uses: actions-ecosystem/action-add-labels@v1
      #   with:
      #     labels: automerge
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.OWNER_TOKEN }}
      #     repository: knot-test-organization/prueba
      #     event-type: approve-event
      #     client-payload: '{"repository": "${{ github.event.repository.name }}", "owner": "${{ github.event.repository.owner.login }}",  "pull_number": ${{ github.event.number }}}'


  merge:
    needs: verify-automerge-label
    runs-on: ubuntu-latest

    steps:
      - name: "Merge pull request"
        uses: "actions/github-script@v6"
        with:
          # github-token: "${{ secrets.OWNER_TOKEN }}"
          script: |
            const pullRequest = ${{ github.event.number }}
            const owner = "${{ github.event.repository.owner.login }}"
            const repository = "${{ github.event.repository.name }}"

            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: owner,
              pull_number: pullRequest,
              repo: repository,
            })
