# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_call:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'tag'
        # Default value if no value is explicitly provided
        default: 'tag'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      tagevent:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'tagevent'
        # Default value if no value is explicitly provided
        default: 'tagevent'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - name: Checkout github tag
      uses: actions/checkout@v4
      with:
        ref: tag
